# This is a basic workflow to help you get started with Actions

name: infracost

# Controls when the workflow will run
on: [pull_request, push]
env:
    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# Allows you to run this workflow manually from the Actions tabworkflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install infracost
        run: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      # Runs a set of commands using the runners shell
      - name: configure infracost
        run: |
          infracost configure set api_key $INFRACOST_API_KEY
          infracost configure set currency INR

      - name: Get Pull Request Number
        run: |
          echo ::set-env name=PULL_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo $PULL_NUMBER
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: configure infracost
        run: |
          infracost breakdown --path=. --format=json --out-file=./infracost-base.json

      - name: comment infracost
        run: |
          infracost comment github --path infracost.json --repo $GITHUB_REPOSITORY --pull-request $PULL_NUMBER --github-token $GITHUB_TOKEN --behavior update
