# This is a basic workflow to help you get started with Actions

name: infracost

# Controls when the workflow will run
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '!main'

env:
    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    ACTIONS_ALLOW_UNSECURE_COMMANDS: true

# Allows you to run this workflow manually from the Actions tabworkflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform installation
        run: |
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

    # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan -out=jenkins.plan
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      # Runs a single command using the runners shell
      - name: Install infracost
        run: curl -fsSL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      # Runs a set of commands using the runners shell
      - name: configure infracost
        run: |
          infracost configure set api_key $INFRACOST_API_KEY
          infracost configure set currency INR

      - name: Get Pull Request Number
        run: |
          echo $GITHUB_REF
          echo $GITHUB_REF | awk '{ $3 }'
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: configure infracost
        run: |
          infracost breakdown --path=./jenkins.plan --format=json --out-file=/tmp/infracost-base.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: comment infracost
        run: |
          infracost comment github --path /tmp/infracost-base.json --repo $GITHUB_REPOSITORY --pull-request 2 --github-token $GITHUB_TOKEN --behavior update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
